services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            -   '8080:8080'
        depends_on:
            database:
                condition: service_healthy
        environment:
            -   SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/tenants
            -   SPRING_DATASOURCE_USERNAME=root
            -   SPRING_DATASOURCE_PASSWORD=rootpassword
        networks:
            -   app-network

    database:
#        container_name: mysql_database
        image: mysql:8.0.40
        ports:
            -   '3307:3306'
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword  # MySQL root password
            MYSQL_DATABASE: tenants  # Database name to be created on startup
            MYSQL_PASSWORD: rootpassword  # Password for the user
        volumes:
            -   mysql-data:/var/lib/mysql
        networks:
            -   app-network
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            retries: 10
            interval: 3s
            timeout: 30s
volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge