services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart: always
        volumes:
            - storage:/extras
        depends_on:
            - db

    db:
        image: mysql:8.0.40
        restart: always
        volumes:
            - storage:/mysql
        ports:
            - "3308:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=Passw0rd
            - MYSQL_DATABASE=tenants

volumes:
    storage:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: "./extras"